### ISSUE TITLE
Duda PK de Cabina

### ISSUE THREAD

**Issue by facuhump2409** [Andy-chavez/TPGDD-1C2019#1]
Muchachos tengo una duda de como quieren hacer la PK de cabina. hay dos opciones:

1. es hacer una compuesta directamente de la maestra pero que tendria que ser de todos los componentes (osea 4 id tipoCabina,numero,piso,id crucero)
2. Hacemos una clave subrrogada con un identity en ID_Cabina (yo prefiero esta)

**Comment by Andy-chavez** [comment]
Buenass, creo que es mucho mas linda la segunda opción. Personalmente tambien preferiria esa

**Comment by Bade99** [comment]
Eso se responde solo, dame la 2

**Comment by facuhump2409** [comment]
Jajajaj sisi me parecia pero por las dudas como la tabla la habian puesto sin identity tenia duda si queria hacerlo de la otra forma.
Issue cerrado
