### ISSUE TITLE
[migracion]Agregar funcionalidades

### ISSUE THREAD

**Issue by Andy-chavez** [Andy-chavez/TPGDD-1C2019#10]
Tenemos que agregar los inserts de las funcionalidades del cliente

**Comment by facuhump2409** [comment]
No se lo habiamos puesto? Tipo la unica funcionalidad del cliente es comprar pasaje y pagar reserva.

**Comment by Andy-chavez** [comment]
Para el cliente como tal no. Si a “usuario” pero que no son lo mismo
