### ISSUE TITLE
Tema drops (incluidos los de procedure, trigger)

### ISSUE THREAD

**Issue by facuhump2409** [Andy-chavez/TPGDD-1C2019#11]
habria que ver quizas de ponerlos todos juntos para que quede mas ordenado el script

**Comment by Andy-chavez** [comment]
si pero eso mas para el final, de momento creo que conviene dejarlos cerca asi sabemos que tiene drop y que no, dps los ponemos lindos pero no de momento, mismo si tenemos que dropearlos por alguna cosa, es mejor que este cerca

**Comment by facuhump2409** [comment]
Sisi era para ver mas al final y no olvidarnos

**Comment by Andy-chavez** [comment]
okki
