### ISSUE TITLE
[APLICATIVO] Actualizado

### ISSUE THREAD

**Issue by Andy-chavez** [Andy-chavez/TPGDD-1C2019#18]
# Restantes:
- [x] Revisar un poco todo, estuve arreglando ya unas cosas, asique por las dudas diria de ver un poco todo antes de entregar
- [x] modificar rol 

- [x] crear rol:

> Sigue sin resolver correctamente el agregado de funcionalidades, porque hay 10 combos de funcionalidad y no 8 o 12? Ademas en los 10 combos puedo elegir la misma funcionalidad. Deben plantear la resolución de manera mas agil y dinámica. Deben aplicar la misma logica en modificar.

- [x] ABM DE RECORRIDO:

> Mal implementado, si bien los datos migrados son correctos, en el abm habla de agregar ciudades no tramos, ende, se debería poder seleccionar cualquier ciudad como origen y de la misma forma con la ciudad destino (tengan en cuenta que puede haber más de 2 ciudades) Uds presentan combinaciones preestablecidas, que si bien son correctas para los datos migrados, eso no implica que se pueden establecer otras combinaciones posibles con el conjunto de ciudades que deben migrar.

> La logica que establecieron para la modificacion no es clara, todo porque uds no contemplan otros "tramos" a los migrados, siendo que tienen un set de ciudades mucho mayor. Repetimos, un recorrido es un conjunto de ciudades o puertos donde amarra un crucero, la agrupación logica que le den uds es independiente al requerimiento.

> Como se valida el ingreso de importe que no sea menor a 0 

- [x] alta de crucero:

> No se completa un tipo de cabina y se informa un error "la cadena de entrada no tiene el formato correcto" Que tipo de error es ese? que significa?

- [x] GENERAR VIAJE:

> La lista de cruceros que presentan para seleccion es mayor a la cantidad total de crucero que en realidad existe ademas de que no contemplan aquellos crucero que se dieron de alta durante las pruebas. Comparen la lista de cruceros disponibles para modificar en el abm de cruceros y la lista que presentan para crear un viaje.

- [x] COMPRA y RESERVA DE PASAJE:

> Mezclan informacion en un gran grid, si estan mostrando info del viaje, no debe haber info de butucas, por ej... Esa informacion es del crucero no del viaje, primero deben listar los viajes posibles para las fechas indicadas, luego seleccionar el crucero y luego las butacas, Solo imaginen que pasa si tengo 10 cruceros con 3000 camarotes, es imposible resolver la consulta, teniendo un uso ineficiente de recursos.

## Para dps:
- [x] Plus que nos podrian corregir es lo de las funcionalidades en los roles, al momento de iniciar el aplicativo no estamos teniendo en cuenta que quien inicia tiene ciertas funcionalidades restringidas

**Comment by facuhump2409** [comment]
FALTA TERMINAR HACER UNA RESERVA Y PAGARLA.  Y TESTEAR UN POCO TODO

**Comment by facuhump2409** [comment]
Termine crear rol si pueden veanlo, nose si tambien hay que arreglar modificar porque creo que ya esta bien, bah nose si se saca de a una las funcionalidades o como una lista como en crear.
