### ISSUE TITLE
Tabla recorrido y tramo

### ISSUE THREAD

**Issue by facuhump2409** [Andy-chavez/TPGDD-1C2019#2]
Muchachos despues vean como me parece que deberian quedar estas tablas, no lo modifique, pero lo comente en los insert de recorrido y tramo que son los ultimos. Ahi esta bien explicado cual es el problema. Pero en resumen, seria que es un quilombo(bah o al menos que alguno sepa) ponerle a los recorridos de donde hasta donde van teniendo en cuenta lo de los tramos.

**Comment by Bade99** [comment]
Para mi tenemos que buscar alguna forma de guardar en el recorrido el orden en que van los tramos, sino en el aplicativo cuando después te llegue la lista de tramos no tenés idea como ordenarlos.

Ó que un tramo apunte al siguiente.

**Comment by facuhump2409** [comment]
Yo pensaba que quizas no era tan dificil hacer lo del orden. Basicamente porque lo ves cuando el puerto hasta es igual al puerto desde ahi vas armando el recorrido

**Comment by Bade99** [comment]
Pero si tenés cosas que van y vuelven me parece que vas a tener problemas.





Gil

**Comment by andresparada** [comment]
Es verdad eso,  hay q ver como el admin crea los recorridos, yo pensaba en q iba agregando 1 por 1 y los vas agregando a una lista por orden con condición del destino-origen, y si hace la vuelta recorrer la lista de firma inversa, o q vuelva a poner la vuelta 1 por 1, pero si tienen una forma más fácil o mejor, estoy dentro
