### ISSUE TITLE
[RESUELTO] ver tema vencimiento en el aplicativo

### ISSUE THREAD

**Issue by facuhump2409** [Andy-chavez/TPGDD-1C2019#4]
NO PODEMOS HACER UN TRIGGER EN EL BATCH!!!!!!!!!

**Comment by Andy-chavez** [comment]
y si queremos hacer un trigger basicamente tenemos que ni pensar en hacerlo? okk .-.

**Comment by facuhump2409** [comment]
jajaj ayer ya queriamos matar al ssms y no sabemos bien como hacer para que te acepte la declaracion dentro del trigger asique tendriamos que hacerlo en el aplicativo o buscar otra forma de resolverlo.

**Comment by Andy-chavez** [comment]
Ya funciona chiquis! era una boludes de escribir tres palabras mas no mass, dps subo la modificacion
