### ISSUE TITLE
[TABLA USUARIO] Baja por login

### ISSUE THREAD

**Issue by Andy-chavez** [Andy-chavez/TPGDD-1C2019#6]
al momento de que el usuario ya la haya cagado ingresando la contra mal mas de tres veces, tenemos que borrarlo o darle baja logica? no pude encontrar si es que decian algo especifico de eso, hice el SP con borrado pero veanlo por las dudas por si le pifie en alguna

**Comment by facuhump2409** [comment]
"Luego de 3 intentos fallidos en cualquier momento, el usuario debe ser inhabilitado ", (del enunciado) creo que lo unico que hay que agregar es una variable que sea inhabilitado char(1) check(inhabilitado in ('s','n')) y que por default sea N

**Comment by Andy-chavez** [comment]
sisi lei eso pero baja logica o fisica?

**Comment by facuhump2409** [comment]
Logica
