### ISSUE TITLE
[FALTANTES] tendriamos que agregar algunos drops

### ISSUE THREAD

**Issue by Andy-chavez** [Andy-chavez/TPGDD-1C2019#7]
Hay que hacerle el drop a la temp de tramo, al trigger y no se si al procedure tmb

**Comment by facuhump2409** [comment]
A la temp seguro que si despues de hacer el insert, al trigger no creo que sea necesario y a los procedure hay que hacerlos

**Comment by Andy-chavez** [comment]
del trigger tira el error de que ya esta creado tmb. De todas formas, el issue era mas para que cuando nos acordemos lo hagamos
